### ISSUE TITLE
PyPI missing CHANGES.md

### ISSUE THREAD

**Issue by jayvdb** [py-paulo/aiowatcher#1]
```py
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    long_description='\n\n'.join((read('README.md'), read('CHANGES.md'))),
  File "setup.py", line 22, in read
    return (HERE / f).read_text('utf-8').strip()
  File "/usr/lib64/python3.8/pathlib.py", line 1235, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib64/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib64/python3.8/pathlib.py", line 1077, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.md'
```

**Comment by py-paulo** [comment]
em qual situação esse erro ocorre?

**Comment by jayvdb** [comment]
1. `wget https://files.pythonhosted.org/packages/5e/d9/d531a214c3087e39b53fd331d5623595e90f2774feac561af459b2eda57c/aiowatcher-0.0.5.tar.gz`
2. `tar -xzf aiowatcher*z`
3. `cd aoiwatcher*`
4. `python3 setup.py install`
